baseURL = "https://marcusmohall.github.io"
title = "Marcus Mohall"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
capitalizeListTitles = true # Capitalize first letter etc.
titleCaseStyle = "firstupper" # Capitalize first letter etc.
pygmentsCodeFences = true
pygmentsUseClasses = true
ignoreErrors = ["error-missing-instagram-accesstoken"]
enableRobotsTXT = true

[params]
  description = "Website for Marcus Mohall. Political economy of (public) transportation, housing, and urban planning and policy more broadly."
  dark = "auto" # can also be "auto" 
  highlight = true
  date_format = "02 Jan 2006"

[menu]
  
#   [[menu.main]]
#    identifier = "about"
#    name = "about"
#    title = "about"
#    url = "/about/"
#    weight = 5
    
#  [[menu.main]]
#    identifier = "posts"
#    name = "posts"
#    title = "posts"
#    url = "/posts/"
#    weight = 10
    
#	[[menu.main]]
#    identifier = "CV"
#    name = "CV"
#    title = "CV"
#    url = "/CV/"
#    weight = 15

	[[menu.main]]
    identifier = "Contact"
    name = "Contact"
    title = "Contact"
    url = "/contact/"
    weight = 20

	[[menu.main]]
    identifier = "Publications"
    name = "Publications"
    title = "Publications"
    url = "/publications/"
    weight = 15

[permalinks]
  posts =  "/:year/:month/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
